# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c066cf0da5a9f07e906c6884c4c1a9037d830ff2eea7cdb7ee47eed1eadc824eef2bb531161f9f98ec39e68f610c92c71aad6c00ee6e3c22ca6c4c1514b39f69

test:
  secret_key_base: 104deb526a65ccd8269cf24fc45e9338cf9f573e4b519a3efcd4c0ceca0bee9bbdfcf58b24d754c62888262bd17bf50fe7f717a680e2912c0e33c8ddf0be3038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
